owner: imsankz
repo: status

sites:
  - name: KreatorLane App
    url: https://kreatorlane.com
  - name: Supabase API
    url: https://vbsntculbrpmafxmuokk.supabase.co/auth/v1/health
    headers:
      - Authorization: "Bearer sb_publishable_vfpqxga7R6MvnoE8ibRUMA_mY4PnE-O"
      - apikey: "sb_publishable_vfpqxga7R6MvnoE8ibRUMA_mY4PnE-O"

assignees:
  - imsankz

status-website:
  cname: status.kreatorlane.com
  baseUrl: /
  logoUrl: https://kreatorlane.com/favicon.svg
  name: KreatorLane Status
  introHtml: "Monitoring the core services of the Creator Operating System."
  navbar:
    - title: App
      href: https://kreatorlane.com
    - title: GitHub
      href: https://github.com/imsankz/status
